# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-12-13 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import enumfields.fields
import shuup_mailchimp.models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_mailchimp', '0003_unique_email_and_add_contact_foreign_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailchimpStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='The email that will receive order confirmations and promotional materials (if permitted).', max_length=256, verbose_name='email')),
                ('old_status', enumfields.fields.EnumField(default='no_status', enum=shuup_mailchimp.models.MailchimpStatus, max_length=12)),
                ('new_status', enumfields.fields.EnumField(default='no_status', enum=shuup_mailchimp.models.MailchimpStatus, max_length=12)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
            ],
        ),
    ]
